version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 30
      runas: root
      mode: 777
  ApplicationStart:
    - location: start.sh
      timeout: 30
      runas: root
      mode: 777
  ApplicationStop:
    - location: stop.sh
      timeout: 30
      runas: root
      mode: 777
