version: 0.0
os: linux
files:
  - source: /appspec.yml
    destination: /home/ubuntu/app/appspec.yml
  - source: /install.sh
    destination: /home/ubuntu/app/install.sh
  - source: /package.json
    destination: /home/ubuntu/app/package.json
  - source: /server.js
    destination: /home/ubuntu/app/server.js
  - source: /start.sh
    destination: /home/ubuntu/app/start.sh
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root
    - location: start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root
